package de.uni_oldenburg.tugtest.model;

public enum MeasurementType {
    ACCELERATION, GRAVITY, ROTATION, EARTH_FRAME_ALIGNED_ACC, EARTH_FRAME_ALIGNED_GYRO,
    STEPS, HEARTBEAT, MISC_START_MEASUREMENT
}
